/*
* ActionTypes.tsx
*
* @author Anusree
* @version 1.0.0
*/

// Print
export const INCREMENT = 'INC_COUNTER';
export const DECREMENT = 'DEC_COUNTER';

// Person
export const ADD_PERSON = 'ADD_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';

// Blog
export const INIT_BLOGPAGE = 'INIT_BLOGPAGE';
export const UPDATE_BLOGPAGE = 'UPDATE_BLOGPAGE';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const FETCH_BLOGPAGE_FAILED = 'FETCH_BLOGPAGE_FAILED';
export const FETCH_BLOGPAGE_EMPTY = 'FETCH_BLOGPAGE_EMPTY';

// Blog Detail
export const INIT_BLOGDETAILPAGE = 'INIT_BLOGDETAILPAGE';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const FETCH_BLOGDETAILPAGE_FAILED = 'FETCH_BLOGDETAILPAGE_FAILED';
export const FETCH_BLOGDETAILPAGE_EMPTY = 'FETCH_BLOGDETAILPAGE_EMPTY';

// Service
export const INIT_SERVICEPAGE = 'INIT_SERVICEPAGE';
export const UPDATE_SERVICEPAGE = 'UPDATE_SERVICEPAGE';
export const SET_SELECTED_SERVICECATEGORY = 'SET_SELECTED_SERVICECATEGORY';
export const FETCH_SERVICEPAGE_FAILED = 'FETCH_SERVICEPAGE_FAILED';
export const FETCH_SERVICEPAGE_EMPTY = 'FETCH_SERVICEPAGE_EMPTY';

// Service Detail
export const INIT_SERVICEDETAILPAGE = 'INIT_SERVICEDETAILPAGE';
export const FETCH_SERVICEDETAILPAGE_FAILED = 'FETCH_SERVICEDETAILPAGE_FAILED';
export const FETCH_SERVICEDETAILPAGE_EMPTY = 'FETCH_SERVICEDETAILPAGE_EMPTY';

// Covid
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const INIT_COVIDPAGE = 'INIT_COVIDPAGE';
export const COVID_UPDATED_DETAILS = 'COVID_UPDATED_DETAILS';
export const FETCH_COVIDPAGE_FAILED = 'FETCH_COVIDPAGE_FAILED';
export const FETCH_COVIDPAGE_EMPTY = 'FETCH_COVIDPAGE_EMPTY';

// Project
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const INIT_PROJECTPAGE = 'INIT_PROJECTPAGE';
export const UPDATE_PROJECT_DETAILS = 'UPDATE_PROJECT_DETAILS';
export const FETCH_PROJECTPAGE_FAILED = 'FETCH_PROJECTPAGE_FAILED';
export const FETCH_PROJECTPAGE_EMPTY = 'FETCH_PROJECTPAGE_EMPTY';

// Product
export const INIT_PRODUCTPAGE = 'INIT_PRODUCTPAGE';
export const UPDATE_PRODUCTPAGE = 'UPDATE_PRODUCTPAGE';
export const SET_SELECTED_PRODUCTCATEGORY = 'SET_SELECTED_PRODUCTCATEGORY';
export const PRODUCT_SEARCH = 'PRODUCT_SEARCH';
export const FETCH_PRODUCTPAGE_FAILED = 'FETCH_PRODUCTPAGE_FAILED';
export const FETCH_PRODUCTPAGE_EMPTY = 'FETCH_PRODUCTPAGE_EMPTY';

// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
