FROM node:12.18-alpine as dev
WORKDIR /work/
COPY ./package.json /work/package.json
RUN npm install
RUN npm install -g nodemon
COPY ./src/ /work/src/
# ENTRYPOINT [ "nodemon","--inspect=0.0.0.0","./src/server.js"]
CMD ["nodemon", "-L", "--inspect=0.0.0.0", "./src/server.js"]

FROM node:12.18-alpine as prod
WORKDIR /work/
COPY ./package.json /work/package.json
RUN npm install
COPY ./src/ /work/src/
CMD ["node", "./src/server.js"]
# CMD ["npm", "run", "start"]
# CMD node .
